language: java

sudo: false

jdk:
  - openjdk8
  - oraclejdk8

deploy:
  provider: releases
  api_key: $GITHUB_OAUTH_TOKEN 
  file: ./build/libs/storm-jedis.jar
  skip_cleanup: true
  on:
    tags: true
