language: java

sudo: false

##
# OpenJDK 8 is not available (yet).
jdk:
  - openjdk7
  - oraclejdk7
  - oraclejdk8

##
# When a release is tagged, push to GitHub Releases.
deploy:
  provider: releases
  api_key: $GITHUB_OAUTH_TOKEN 
  file: ./build/libs/storm-jedis.jar
  skip_cleanup: true
  on:
    tags: true
